---
- name: Manage Pi-hole adlists
  hosts: pihole
  become: true
  vars_files:
    - vars.yml

  tasks:

    - name: Ensure sqlite3 is installed
      ansible.builtin.package:
        name: sqlite3
        state: present

    - name: Remove all existing adlists if cleanup is enabled
      ansible.builtin.shell: "sqlite3 /etc/pihole/gravity.db 'DELETE FROM adlist;'"
      when: cleanup_adlists | bool

    - name: Insert adlist into gravity.db
      ansible.builtin.shell: "sqlite3 /etc/pihole/gravity.db \"INSERT OR IGNORE INTO adlist (address, enabled, comment) VALUES ('{{ item }}', 1, 'Added via Ansible');\""
      loop: "{{ adlists }}"
      args:
        executable: /bin/bash

    - name: Update Pi-hole gravity
      ansible.builtin.shell: "pihole -g"

