---
- name: Configure Pi-hole adlists
  hosts: pihole
  become: true
  vars_files:
    - vars.yml
    - adlists.yml

  tasks:
    - name: Remove all existing adlists if cleanup enabled
      ansible.builtin.shell: "sqlite3 /etc/pihole/gravity.db 'DELETE FROM adlist;'"
      when: cleanup_adlists | bool

    - name: Insert adlists into gravity.db
      ansible.builtin.shell: "sqlite3 /etc/pihole/gravity.db \"INSERT OR IGNORE INTO adlist (address, enabled, comment) VALUES ('{{ item }}', 1, 'Added via Ansible');\""
      loop: "{{ adlists }}"
      args:
        executable: /bin/bash

    - name: Update Pi-hole gravity
      ansible.builtin.shell: "pihole -g"

    - name: Restart Pi-hole FTL service
      ansible.builtin.service:
        name: pihole-FTL
        state: restarted

