---
galaxy_info:
  author: guruprasadcp
  description: Ansible role to install and configure Pi-hole using pihole.toml and manage adlists with sqlite
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - pihole
    - dns
    - adblock
